# Copy this file to config.yml to get started and then add your own configuration.


settings:
  update_interval: 300
  market_pairs:
    - ETH/BTC
    - LTC/BTC
    - XMR/BTC

exchanges:
  bittrex:
    required:
      enabled: true
